apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  selector:
    app: python-backend
  ports:
    - protocol: TCP
      port: 22
      targetPort: 5000  # Your application's internal port
  type: NodePort  # Expose the service locally